### ISSUE TITLE
图床域名变更

### ISSUE THREAD

**Issue by starlightor** [chclt/jandan-plus#8]
煎蛋图床最近加了一个toto.im，现在用插件的话点击会提示加载失败，什么时候可以加到插件里面啊？

**Comment by yupolee** [comment]
同样遇到了这个问题，点击GIF提示加载失败，禁用插件可以正常播放

**Comment by chclt** [comment]
感谢反馈！代码已更新，应用商店版本预计本周内上线~

fa4fbb31237fb290f940e0bddaf75fd2e536b402
